export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_PIZZA: 'SET_PIZZA',
	SET_GIFT: 'SET_GIFT',
	SET_DRINK: 'SET_DRINK',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
};
